//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="BattlePassService"/> </summary
    public sealed class BattlePassServiceClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public BattlePassServiceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public BattlePassServiceClient(Beamable.Common.Dependencies.IDependencyProvider provider) : 
                base(provider)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "BattlePassService";
            }
        }
        
        /// <summary>
        /// Call the BattlePassService_IsBattlepassValid method on the BattlePassService microservice
        /// <see cref="BattlePassService.BattlePassService_IsBattlepassValid"/>
        /// </summary>
        public Beamable.Common.Promise<bool> BattlePassService_IsBattlepassValid(Beamable.Common.Content.ContentRef<Beamable.Common.Battlepass> battlePassContent)
        {
            object raw_battlePassContent = battlePassContent;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("battlePassContent", raw_battlePassContent);
            return this.Request<bool>("BattlePassService", "IsBattlepassValid", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersBattlePassServiceClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterBeamable_Common_Content_ContentRef_Beamable_Common_Battlepass : MicroserviceClientDataWrapper<Beamable.Common.Content.ContentRef<Beamable.Common.Battlepass>>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForBattlePassServiceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute(50, Beamable.Common.Dependencies.RegistrationOrigin.EDITOR | Beamable.Common.Dependencies.RegistrationOrigin.RUNTIME)]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            System.Func<Beamable.Common.Dependencies.IDependencyProvider, BattlePassServiceClient> factory = p => new BattlePassServiceClient(p);
            builder.AddScoped<BattlePassServiceClient>(factory);
        }
        
        public static BattlePassServiceClient BattlePassService(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<BattlePassServiceClient>();
        }
    }
}
